name = "minimal-local"
license = "MIT"
licenselink = "https://github.com/powersj/minimal-local/blob/master/LICENSE.md"
description = "Personal blog theme powered by Hugo"
homepage = "https://github.com/powersj/minimal-local"
tags = ["blog", "minimal", "personal", "responsive", "local"]
features = ["responsive"]
min_version = "0.24.1"

[author]
  name = "Joshua Powers"
  homepage = "https://powersj.io/"

[author-orig]
  name = "Calin Tataru"
  homepage = "https://calintat.github.io/"
